apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  REFORM_ENVIRONMENT : "aat"
  APPLICATION_INSIGHTS_IKEY : "da42f3e5-892a-4201-a2df-05d2c28a410b"
  SLOT : "PRODUCTION"
  REFORM_SERVICE_NAME : "vs"
  REFORM_TEAM : "div"
  APPINSIGHTS_INSTRUMENTATIONKEY : "da42f3e5-892a-4201-a2df-05d2c28a410b"